### ISSUE TITLE
Cannot connect to gost because Warp is grabbing incoming traffic

### ISSUE THREAD

**Issue by ostrolucky** [cmj2002/warp-docker#23]
Inside container
```
warp@1db191c9c609:/$ curl --socks5-hostname 127.0.0.1:1080 https://cloudflare.com/cdn-cgi/trace
fl=636f241
h=cloudflare.com
ip=8.29.109.153
ts=1720827095.986
visit_scheme=https
uag=curl/7.81.0
colo=FRA
sliver=none
http=http/2
loc=DE
tls=TLSv1.3
sni=plaintext
warp=on
gateway=on
rbi=off
kex=X25519
```

Outside container
```
❯ curl --socks5-hostname 127.0.0.1:1080 https://cloudflare.com/cdn-cgi/trace -v
*   Trying 127.0.0.1:1080...
* Connected to 127.0.0.1 (127.0.0.1) port 1080
* Recv failure: Connection reset by peer
* SOCKS: Failed receiving initial SOCKS5 response: Failure when receiving data from the peer
* Closing connection
curl: (97) Recv failure: Connection reset by pee
```

Once I kill warp-svc process inside container, then previous command works (but then it doesn't go through cloudfare network of course).

Do you have any advice what to do in this case?

**Comment by cmj2002** [comment]
The command you are using in the container is going through gost (you specified `--socks5-hostname`). Therefore, gost is working, and traffic is being transmitted through warp. However, outside the container (assuming you are running the command on the host machine), it cannot connect to gost, so the **issue lies in the connection between the container and the host machine**. Have you made any modifications to `docker-compose.yml` (such as modifying or deleting mapped ports), or do you have special firewall or iptables settings on your machine that prevent Docker port mapping from functioning properly?

**Comment by ostrolucky** [comment]
Like I said when I kill warp-svc process inside container, connection from outside container starts working, so it must be caused by warp catching this income traffic from whatever else that's not coming through `lo` interface. I've spun up separate service in same docker-compose network and I cannot connect from over there either unless I stop warp.

**Comment by cmj2002** [comment]
I can't think of any reason that caused it. I also run a similar setup myself, where another container accesses the warp inside the container, and it works well:

```
root@2c285c19ef85:/app# curl --socks5-hostname warp-socks:1080 https://cloudflare.com/cdn-cgi/trace
fl=650f66
h=cloudflare.com
ip=104.28.202.178
ts=1720924102.809
visit_scheme=https
uag=curl/7.88.1
colo=EWR
sliver=none
http=http/2
loc=US
tls=TLSv1.3
sni=plaintext
warp=plus
gateway=off
rbi=off
kex=X25519
```

Here is my configuration for your reference, hoping it will be helpful to you.

```yaml
version: '3.9'

services:
    rsshub:
        image: diygod/rsshub:chromium-bundled
        restart: always
        container_name: rsshub
        environment:
            PROXY_URI: 'http://warp-socks:1080'
        depends_on:
            - warp-socks
        networks:
            - exposed
            - rsshub
    warp-socks:
        image: caomingjun/warp:latest
        container_name: warp-socks
        restart: always
        volumes:
            - /home/cmj/warp/var:/var/lib/cloudflare-warp
        cap_add:
            - NET_ADMIN
        sysctls:
            net.ipv6.conf.all.disable_ipv6: 0
            net.ipv4.conf.all.src_valid_mark: 1
        networks:
            - rsshub
        environment:
            - WARP_SLEEP=2
            - WARP_LICENSE_KEY=***

networks:
    rsshub:
        name: rsshub
    exposed:
        name: exposed
        external: true
```

where:
- `expose` is the network where nginx is located
- I use http because rsshub cannot use socks, but as shown in the above command line result, socks5 can be accessed within the container.
