### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by bamboox** [cmj2002/warp-docker#30]
sudo: unable to send audit message: Operation not permitted
sudo: unable to send audit message: Operation not permitted
mknod: /dev/net/tun: Operation not permitted
sudo: unable to send audit message: Operation not permitted
sudo: unable to send audit message: Operation not permitted
mknod: /dev/net/tun: Operation not permitted

**Comment by cmj2002** [comment]
你在什么宿主机上运行的？什么操作系统、docker哪个版本、cpu指令集（amd64或arm）？

**Comment by cmj2002** [comment]
> 感觉像是用的podman？podman需要加上--privileged或者--device /dev/net/tun，而且初始化的时候不能运行mknod: /dev/net/tun，因为--privileged权限下或者映射状态下tun是已存在的

如果是 podman 的话试试这个解决方案？

https://github.com/pi-hole/docker-pi-hole/issues/1007#issuecomment-1053208134

**Comment by cmj2002** [comment]
> > > > 感觉像是用的podman？podman需要加上--privileged或者--device /dev/net/tun，而且初始化的时候不能运行mknod: /dev/net/tun，因为--privileged权限下或者映射状态下tun是已存在的
> > > 
> > > 
> > > 如果是 podman 的话试试这个解决方案？
> > > [pi-hole/docker-pi-hole#1007 (comment)](https://github.com/pi-hole/docker-pi-hole/issues/1007#issuecomment-1053208134)
> > 
> > 
> > mknod: /dev/net/tun: Operation not permitted 这个方案不行，加审计日志权限解决不了创建虚拟网卡权限的问题，要么挂载tun，要么--privileged，一般用--privileged能解决，但是安全性不高
> 
> 在添加--privileged状态下， 报错变成了mknod: /dev/net/tun: File exists 所以我在提交的PR中加了一个判断以适应podman的规则

我还是倾向于找到相应需要的cap，应该可以用strace找到，我明天研究一下。你可以先试试把 NET_RAW 加上。

**Comment by cmj2002** [comment]
如果实在找不到我就 merge 你的 PR

**Comment by cmj2002** [comment]
https://github.com/containers/common/pull/1240#issue-1460136014

应该还需要 MKNOD

**Comment by cmj2002** [comment]
我做了以下的实验：

```yaml
    cap_drop:
      - ALL
    cap_add:
      # defualt cap of podman 
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - FSETID
      - KILL
      - NET_BIND_SERVICE
      - SETFCAP
      - SETGID
      - SETPCAP
      - SETUID
      - SYS_CHROOT

      # docker have these cap as default additonally
      - MKNOD
      # - NET_RAW
      - AUDIT_WRITE

      # additional required cap for warp
      - NET_ADMIN
```

是可以跑通的。

总结一下就是 podman 比 Docker 默认少了三个 CAP
- [Docker 的默认 CAP](https://github.com/moby/moby/blob/c7e42d855ec41c28702a1f6f6c2c28ecc7bd9424/oci/caps/defaults.go)
- [Podman 的默认 CAP](https://github.com/rhatdan/common/blob/28484bfcec5ee41ef0258d6bb57f388abb1ac977/pkg/config/containers.conf#L61)

其中 `MKNOD`, `AUDIT_WRITE` 是 warp-docker 需要的，`NET_ADMIN` 是两者默认都没有而 warp-docker 也需要。所以 Podman 用户应该使用这样的 CAP:
```yaml
    cap_add:
      # Docker already have it, these are for podman users
      - MKNOD
      - AUDIT_WRITE
      # additional required cap for warp, both for podman and docker
      - NET_ADMIN
```

@bamboox @tony-sung 请你们在 docker-compose.yml 中加入 `MKNOD` 和 `AUDIT_WRITE` 再试一下（`NET_ADMIN` 也要保留），如果可以我就更新进代码里。
