### ISSUE TITLE
could not connect service from the host

### ISSUE THREAD

**Issue by fireinice** [cmj2002/warp-docker#34]
I've notice the issue #23 is closed.
However I still could not connect the gost  exposed service from the host even with `BETA_FIX_HOST_CONNECTIVITY=1`
the container ip is 172.35.0.37
and the output of the dump is
```
Excluded: [
    10.0.0.0/8,
    100.64.0.0/10,
    169.254.0.0/16,
    172.16.0.0/12,
    192.0.0.0/24,
    192.168.0.0/16,
    224.0.0.0/24,
    240.0.0.0/4,
    239.255.255.250/32,
    255.255.255.255/32,
    fe80::/10,
    fd00::/8,
    ff01::/16,
    ff02::/16,
    ff03::/16,                                                                                                                                 
    ff04::/16,                                                                                                                                 
    ff05::/16,                                                                                                                                 
    fc00::/7,                                                                                                                                  
    17.249.0.0/16,                                                                                                                             
    17.252.0.0/16,                                                                                                                             
    17.57.144.0/22,                                                                                                                            
    17.188.128.0/18,                                                                                                                           
    17.188.20.0/23,                                                                                                                            
    2620:149:a44::/48,                                                                                                                         
    2403:300:a42::/48,                                                                                                                         
    2403:300:a51::/48,                                                                                                                         
    2a01:b740:a42::/48,                                                                                                                        
    240.0.0.0/4,                                                                                                                               
    10.0.0.0/8,                                                                                                                                
    100.64.0.0/10,                                                                                                                             
    172.16.0.0/12,                                                                                                                             
    17.249.0.0/16,                                                                                                                             
    17.252.0.0/16,                                                                                                                             
    169.254.0.0/16,                                                                                                                            
    192.168.0.0/16,                                                                                                                            
    17.188.128.0/18,                                                                                                                           
    17.57.144.0/22,                                                                                                                            
    17.188.20.0/23,                                                                                                                            
    192.0.0.0/24,                                                                                                                              
    224.0.0.0/24,                                                                                                                              
    104.16.80.230/32,                                                                                                                          
    104.17.143.163/32,                                                                                                                         
    162.159.192.7/32,                                                                                                                          
    239.255.255.250/32,                                                                                                                        
    fc00::/7,                                                                                                                                  
    fe80::/10,                                                                                                                                 
    ff02::/15,                                                                                                                                 
    ff04::/15,                                                                                                                                 
    ff01::/16,                                                                                                                                 
    2403:300:a42::/48,                                                                                                                         
    2403:300:a51::/48,                                                                                                                         
    2620:149:a44::/48,                                                                                                                         
    2a01:b740:a42::/48,                                                                                                                        
    2606:4700::6810:50e6/128,                                                                                                                  
    2606:4700::6811:8fa3/128,                                                                                                                  
]   
```

I think `172.35.0.37` is in the range of `172.16.0.0/12`.

and I try to expose a shadowsocks service by gost:
`ss+ohttp://aes-256-gcm:password@172.35.0.37:9876 `

any idea? thanks

**Comment by cmj2002** [comment]
You must have made a mistake. `172.35.0.37` does not belong to `172.16.0.0/12` (the subnet ends at `172.31.255.255`). `172.35.0.37` is a public IP address, which appears to be a home user IP belonging to T-Mobile.

**Comment by fireinice** [comment]
> You must have made a mistake. `172.35.0.37` does not belong to `172.16.0.0/12` (the subnet ends at `172.31.255.255`). `172.35.0.37` is a public IP address, which appears to be a home user IP belonging to T-Mobile.

Thanks! my mistake.

**Comment by fireinice** [comment]
the gost works fine when changed ip to `172.26.0.32`.
but the shadowsocks protocol on gost not works stable.
I've tried install `shadowsocks-libev` in the container and run with the config which works fine in other service. 
but seems not work, config as below:
```json
{
    "server":"0.0.0.0",
    "server_port":8388,
    "local_port":4060,
    "password":"password",
    "timeout":600,
    "method":"aes-256-gcm",
    "fast_open": true,
    "workers": 5,
    "plugin":"obfs-server",
    "plugin_opts": "obfs=http;"
}
```

**Comment by cmj2002** [comment]
Can you run `docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' container_name` to get the correct IP of container and retry?

I recommend setting `0.0.0.0` as gost listening IP and use docker's port forward. IP of container can change when you recreate them. Remember to change the forwarded port if you change the `server_port`.

Also, it seems that you commented with some additional information (I can see it in my email) but somehow it disappear on GitHub.

**Comment by fireinice** [comment]
> Can you run `docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' container_name` to get the correct IP of container and retry?
> 
> I recommend setting `0.0.0.0` as gost listening IP and use docker's port forward. IP of container can change when you recreate them. Remember to change the forwarded port if you change the `server_port`.
> 
> Also, it seems that you commented with some additional information (I can see it in my email) but somehow it disappear on GitHub.

```shell
sudo docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' warp
172.26.0.37
```
It seems the ip is got the correct ip addr.

and now the docker-compose is as below:
```yaml

  warp:                                                                                                                                        
    image: caomingjun/warp:latest                                                                                                              
    container_name: warp                                                                                                                       
    # restart: always                                                                                                                          
    ports:                                                                                                                                     
      - "8338:8338"                                                                                                                                                                                                                                                       
    environment:                                                                                                                                                                                                                                               
      - WARP_SLEEP=2                                                                                                                           
      - GOST_ARGS=-L=ss+ohttp://aes-256-gcm:zhzhqiang%40gmail.com@:8338                                                                                                                                                                    
      - BETA_FIX_HOST_CONNECTIVITY=1                                                                                                                                                                                                              
    cap_add:                                                                                                                                   
      - NET_ADMIN                                                                                                                              
    sysctls:                                                                                                                                   
      - net.ipv6.conf.all.disable_ipv6=0                                                                                                       
      - net.ipv4.conf.all.src_valid_mark=1                                                                                                     
      - net.ipv4.ip_forward=1                                                                                                                  
    volumes:                                                                                                                                   
      - /srv/docker/data/warp/:/var/lib/cloudflare-warp                                                                                        
    networks:                                                                                                                                  
      ss-backend:                                                                                                                              
        ipv4_address: 172.26.0.37 
```

not got lucy,

**Comment by fireinice** [comment]
> Can you run `docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' container_name` to get the correct IP of container and retry?
> 
> I recommend setting `0.0.0.0` as gost listening IP and use docker's port forward. IP of container can change when you recreate them. Remember to change the forwarded port if you change the `server_port`.
> 
> Also, it seems that you commented with some additional information (I can see it in my email) but somehow it disappear on GitHub.

For the other gone replies. 
I've got connection once and I close the issue. 
and then I also tried to build a shadowsocks-libev service, which could not be connected outside.

after that I drawback to the original gost service, and cannot connect again.

I thought the only once 'successful connection' is caused the warp service not established on the time. if the warp not connected from time to time, the shadowsocks protocol could connect right.

**Comment by cmj2002** [comment]
Can you try to see if the default SOCKS5 proxy also has this issue? It’s best to run `curl --socks5-hostname 127.0.0.1:1080 https://cloudflare.com/cdn-cgi/trace` from the host machine for testing, as there may also be a firewall between you and the host machine (regardless of whether it is something you can control).

**Comment by fireinice** [comment]
Yes, the socks5 works fine. with `GOST_ARGS=-L=ss+ohttp://aes-256-gcm:zhzhqiang%40gmail.com@:8338 -L=socks5://:1080`

the socks service works fine on host:
```shell
fii@tc:~$ curl --socks5-hostname 127.0.0.1:1080 https://cloudflare.com/cdn-cgi/trace                                                        
fl=466f140                                                                                                                                     
h=cloudflare.com                                                                                                                               
ip=104.28.217.42                                                                                                                               
ts=1727782106.888                                                                                                                              
visit_scheme=https                                                                                                                             
uag=curl/7.88.1                                                                                                                                
colo=SJC                                                                                                                                       
sliver=none                                                                                                                                    
http=http/2                                                                                                                                    
loc=US                                                                                                                                         
tls=TLSv1.3                                                                                                                                    
sni=plaintext                                                                                                                                  
warp=on                                                                                                                                        
gateway=off                                                                                                                                    
rbi=off                                                                                                                                        
kex=X25519
```

while the shadowsocks not work

**Comment by fireinice** [comment]
I also tried proxy mode before
with run the commands below in the container 
```bash    
warp-cli set-proxy-port 40000
# Set the mode to proxy
warp-cli --accept-tos mode proxy
```
and `GOST_ARGS=-L=ss+ohttp://aes-256-gcm:password@:8338 -F socks://:40000`
the shadowsocks services works.

**Comment by cmj2002** [comment]
This is very strange, I cannot understand. The SOCKS5 works indicates that the container can be accessed from the host machine, and the forwarding of SOCKS5 through shadowsocks suggests that there is no issue with GOST's shadowsocks functionality or your configuration. I can't think of what the problem could be.

**Comment by fireinice** [comment]
yes, that's very strange

**Comment by fireinice** [comment]
I think the default route is the reason.
as
```bash
warp@7abdb58ca03d:/$ sudo ip route
default via 172.26.0.1 dev eth0 
172.26.0.0/24 dev eth0 proto kernel scope link src 172.26.0.32 
```
so all the traffic will route to CloudflareWARP
I'll try to add some route rules to test

**Comment by Ch1ngg** [comment]
我也遇到同样问题。并且尝试换了几台机器进行测试也是如此。服务无法在外面连接
```
version: "3"

services:
  warp:
    image: caomingjun/warp
    container_name: warp
    restart: always
    # add removed rule back (https://github.com/opencontainers/runc/pull/3468)
    device_cgroup_rules:
      - 'c 10:200 rwm'
    ports:
      - "53217:1080"
    environment:
      - WARP_SLEEP=2
      - GOST_ARGS=-L ss+aead-chacha20-poly1305://password@:1080
      - WARP_LICENSE_KEY=xxxxx-xxxxx-xxxx
      # - WARP_ENABLE_NAT=1 # enable nat
    cap_add:
      # Docker already have them, these are for podman users
      - MKNOD
      - AUDIT_WRITE
      # additional required cap for warp, both for podman and docker
      - NET_ADMIN
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv4.conf.all.src_valid_mark=1
      # uncomment for nat
      # - net.ipv4.ip_forward=1
      # - net.ipv6.conf.all.forwarding=1
      # - net.ipv6.conf.all.accept_ra=2
    volumes:
      - ./data:/var/lib/cloudflare-warp
```
我目前使用的配置
