### ISSUE TITLE
Failed to load Registration error=OsError(Os { code: 2, kind: NotFound, message: "No such file or directory" })

### ISSUE THREAD

**Issue by padixa** [cmj2002/warp-docker#4]
一开始以为是ipv6问题, 但删除文件夹重建还是会这样, 它依旧并没有创建setting.json, config.json之类的, 反而反反复复重启.

**Comment by padixa** [comment]
warp配置如下:


```
warp:
    image: caomingjun/warp
    container_name: warp
    restart: no
    ports:
      - '127.0.0.1:1918:1080'
    environment:
      - WARP_SLEEP=2
      # - WARP_LICENSE_KEY= # optional
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
      - net.ipv4.conf.all.src_valid_mark=1
    volumes:
      - ./warp:/var/lib/cloudflare-warp
```

已在docker-compose.yml当前目录下创建文件夹: warp, 并在里面放入文件:mdm.xml, 内容如下(xx为隐藏内容):
```

<dict>
  <key>organization</key>
  <string>xx</string>  
  <key>auth_client_id</key>
  <string>xx</string>
  <key>auth_client_secret</key>
  <string>xx</string>
</dict>
```
