### ISSUE TITLE
"open tun" Operation not permitted

### ISSUE THREAD

**Issue by hugoghx** [cmj2002/warp-docker#41]
First of all, thank you for putting this together. It's a great piece of software! ❤️

I've been using warp-docker for a while now in `tunnel_only` mode and it's all been great until a couple of days ago when connections relying on this proxy started failing.

I started looking into this and the first thing I saw was this error in the warp-docker logs, from warp-svc:
```
ERROR main_loop: warp::warp_service: Connection error error=IoError(AnnotatedIoError { err: Os { code: 1, kind: PermissionDenied, message: "Operation not permitted" }, context: "open tun" })
```

I thought initially this was a permissions issue trying to interact with /dev/net/tun, so I went and had a look: `crw------- 1 root root 10, 200 Dec  7 16:53 /dev/net/tun`

Looked fine. The warp user is a sudoer, but for sanity's sake I chown'd /dev/net/tun to warp and even chmod'd it to 666. Same issue.

I tried a bunch of other combinations of settings and docker configurations (including using MASQUE and WG for the tunnel, and different modes too), but I wasn't able to resolve the issue or find a root cause.

For context, here's my warp-docker Docker Compose definition:
```yaml
  warproxy:
    image: "caomingjun/warp"
    container_name: "warproxy"
    init: true
    cap_add:
      - "NET_ADMIN"
    environment:
      GOST_ARGS: "-L :42069"
    networks:
      - "warproxy_nw"
    sysctls:
      - "net.ipv6.conf.all.disable_ipv6=0"
      - "net.ipv4.conf.all.src_valid_mark=1"
    volumes:
      - "./config/warproxy/settings.json:/var/lib/cloudflare-warp/settings.json"
    tmpfs:
      - "/var/lib/cloudflare-warp:mode=770,size=16M,uid=0,gid=0"
    restart: "unless-stopped"
```

I even went back in warp-docker versions, but now the versions that used to work stopped to do so with the same error. Clearly, this was not an issue with any recent updates to this package.

I then went into trying to figure out what had changed on my system recently and the one thing I remembered was that apt had upgraded the `containerd.io` package on my Ubuntu Server 24.10 from 1.7.23-1 to 1.7.24-1.

I downgraded this package back to 1.7.23-1 and voila, problem solved.

I did not get to the root cause of this issue - I don't know if it's an incompatibility with warp-docker and this new version of `containerd.io` or with Cloudflare WARP itself.

I checked [the changes](https://github.com/containerd/containerd/compare/v1.7.23...v1.7.24) that happened from containerd 1.7.23 to 1.7.24, but I see nothing that would immediately raise any flags. I did notice that runc and a few other dependencies got updated, so maybe more digging 

--

I suspect no other issues like this have cropped up here given that this requires an update action for something that was released pretty recently. Perhaps we'll see more people mention this later as they upgrade their servers.
