### ISSUE TITLE
在docker-compose中，别的应用该怎样设置socks代理呢

### ISSUE THREAD

**Issue by zhuxindong** [cmj2002/warp-docker#5]
```yaml
version: '3'

services:
  ninja:
    image: zhuxindong/ninja:latest
    container_name: ninja
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
      - PROXIES=socks5://127.0.0.1:10801
      # - CONFIG=/serve.toml
      # - PORT=8080
      # - HOST=0.0.0.0
      # - TLS_CERT=
      # - TLS_KEY=
    # volumes:
      # - ${PWD}/ssl:/etc
      # - ${PWD}/serve.toml:/serve.toml
    command: serve run
    ports:
      - "8080:7999"
    depends_on:
      - warp

  warp:
    image: caomingjun/warp
    container_name: warp
    restart: always
    ports:
      - '10801:1080'
    environment:
      - WARP_SLEEP=2
      - WARP_LICENSE_KEY=
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv4.conf.all.src_valid_mark=1
    volumes:
      - ./data:/var/lib/cloudflare-warp
```

我的另一个容器设置- PROXIES=socks5://127.0.0.1:10801 是否正确？还是说设置成 - PROXIES=socks5://warp:10801
