### ISSUE TITLE
Failed to synchronize time with NTP server / Routes changed / TunnelError(ConnectionDriverStopped) issue?

### ISSUE THREAD

**Issue by luckydevil13** [cmj2002/warp-docker#55]
Socks tunnel works up to 10 minutes and goes unhealthy with logs.

censorship blocks?
any suggestions to debug?

```
services:
  warp:
    image: caomingjun/warp
    container_name: warp
    restart: always
    device_cgroup_rules:
      - 'c 10:200 rwm'
    ports:
      - '1080:1080'
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - WARP_SLEEP=5
    cap_add:
      - NET_ADMIN
#    logging:
#      driver: none
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv4.conf.all.src_valid_mark=1
    entrypoint:
      - "/bin/sh"
      - -ecx
      - |
          /entrypoint.sh
          warp-cli tunnel protocol set MASQUE
```

full logs in attach

[warp_1743169067.log](https://github.com/user-attachments/files/19506748/warp_1743169067.log)
